[package]
name = "digital_money"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enc = { path = "../enc" }

num-primes = "0.3.0"
num-bigint-dig = "0.8.4"
num = "0.4.1"